reload("user.plugins")
reload("user.tokyonight")
-- reload("user.onedarkpro")
reload("user.colorscheme")
reload("user.dashboard")
reload("user.options")
reload("user.bufferline")
reload("user.python")
reload("user.code-runner")
reload("user.dap")
reload("user.lf")
-- reload("user.nvimtree")
reload("user.lualine")
reload("user.telescope")
reload("user.terminal")
reload("user.whichkey")
reload("user.disabled")
reload("user.persistence")
reload("user.markdown")
reload("user.chatgpt")
reload("user.tabnine")
reload("user.nvimr")
